settings:
  printers: //android.widget.TextView[@resource-id="softcom.mobile.smart2:id/settings_title" and @text="Impressões"]
  printer_list: softcom.mobile.smart2:id/btn_list_print
  select_printer: softcom.mobile.smart2:id/lista_dispositivo_checkBox
  select_close: softcom.mobile.smart2:id/btnlistadispositivocancelar
  back: softcom.mobile.smart2:id/buttom_back
  exit_settings: softcom.mobile.smart2:id/btn_voltar
  payments_forms: //android.widget.TextView[@resource-id="softcom.mobile.smart2:id/settings_title" and @text="Formas de Pagamento"]
  enable_payment: softcom.mobile.smart2:id/config_dialog_pagamento_swt_ativado
  save_button: softcom.mobile.smart2:id/config_dialog_pagamento_btn_confirmar
  pix_off: //android.widget.TextView[@resource-id="softcom.mobile.smart2:id/config_pagamentos_tv_xPagto" and @text="PIX OFF"]
  ticket: //android.widget.TextView[@resource-id="softcom.mobile.smart2:id/settings_title" and @text="Emissão de Ticket"]
  enable_ticket: //android.widget.TextView[@text="Habilitar ticket para retirada"]
  enable_ticket_reprint: //android.widget.TextView[@text="Permitir reimpressão de ticket"]
  exit_ticket: //android.widget.TextView[@text="Voltar"]
  orders: //android.widget.TextView[@resource-id="softcom.mobile.smart2:id/settings_title" and @text="Pedidos"]
  sales_change_price: softcom.mobile.smart2:id/sales_change_price
  block_stock: softcom.mobile.smart2:id/sales_bloquear_estoque
  fractional_quantity: softcom.mobile.smart2:id/sales_fractional
  bankslip: //android.widget.TextView[@resource-id="softcom.mobile.smart2:id/config_pagamentos_tv_xPagto" and @text="Boleto Bancário"]
  price_table: //android.widget.Switch[@resource-id="softcom.mobile.smart2:id/sales_price_table"]
